python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/datasets/yuseung" --checkpoint_iterations 7000 --eval -m "output/yuseung"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/garden_8" --checkpoint_iterations 7000 --eval -m "output/garden"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/Room" --checkpoint_iterations 7000 --eval -m "output/Room"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/fangzhou-small" --checkpoint_iterations 7000 --eval -m "output/fangzhou_small"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/dtu_scan" --checkpoint_iterations 7000 --eval -m "output/dtu_scan"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/person-small" --checkpoint_iterations 7000 --eval -m "output/person_small"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/three_people_standing" --checkpoint_iterations 7000 --eval -m "output/three_people_standing"
python src/trainer/origin/train.py -s "/home/wucunqi/Desktop/results/plant" --checkpoint_iterations 7000 --eval -m "output/plant"
python src/trainer/origin/train.py -s "/media/wucunqi/data/results/dinosaur" -r "1" --checkpoint_iterations 7000 -m "output/dinosaur"
python src/trainer/origin/train.py -s "/media/wucunqi/data/3D_Datasets/20260310_cunqi" -r "2" --checkpoint_iterations 7000 -m "output/cunqi"